version: '3.9'
services:
  frontend:
    build: ./front-end
    platform: linux/x86_64 
    container_name: ng-cash_frontend
    restart: 'always'
    ports: 
      - 3001:3001 
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"] 
      timeout: 10s
      retries: 5
  backend:
    build: ./backend
    platform: linux/x86_64
    restart: 'always'
    container_name: ng-cash_backend
    ports: 
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PORT=3000
      # Os dados abaixo se referem ao container `postgres` em comunic. interna
      - POSTGRES_PASSWORD=postgres
      - PGUSER=postgres
      - PSQL_HOST=postgres
      - PSQL_DATABASE=ng-cash-db
      - PSQL_PORT=5432
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"] 
      timeout: 10s
      retries: 5
  postgres:
    image: postgres:14.5
    platform: linux/x86_64 
    container_name: postgres
    ports:
      - 5430:5432
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGUSER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ng-cash-db
    restart: 'always'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    cap_add:
      - SYS_NICE # Deve omitir alertas menores